name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: krynv/build-godot-action@v1.0.0
        with:
          name: PS2.Visual.Novel.Tool
          preset: windows
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS2.Visual.Novel.Tool
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: Godot
    runs-on: ubuntu-latest
    steps:
      - name: Download from Github
        uses: actions/download-artifact@v4
        with:
          path: assets

      - name: Re-zip artifacts
        run: |
          cd assets
          for dir in */ ; do
            zip -r "${dir%/}.zip" "$dir"
          done
        shell: bash

      - name: Release to Github
        uses: softprops/action-gh-release@v2
        with:
          files: |
            assets/*.zip
